sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules


"Yo que iba tan tranquilo al final de mi vida terrenal. 
De pronto dudo y basilo. 
Es verdad que no hay asilo para el alma?... 
Que morir es dejar de existir?... 
Es decir, 
que la existencia no tiene la trascendencia que me dejaron intuir?... 
No! 
Eso no, por favor.  
Yo  con mi libre ğšğ¥ğ›ğğğ«ğ¢ğ¨ 
me atrevo a decir dios mio, 
que debe aver un error. 
Y perdoname senor/a si con eso te incomodo, 
sin embargo de algun modo 
te lo tengo que decir. 
No me vayas a salir con que aqui se acaba todo..."
-BigShakerpere</"U+1F64F = ğŸ˜‰,>